### ISSUE TITLE
LSTM実装可能かどうか調査

### ISSUE THREAD

**Issue by Masa-kuchii** [dondakeshimo/signate-j-quants#10]
LSTMでセクター毎のセンチメント情報を予測可能かどうか調査

module.pyで予測していた部分のコードリーディング及びその応用方法を探る

**Comment by dondakeshimo** [comment]
### 現在使用しているデータ

ファイル名 | 説明
-- | --
headline_features.pkl | 本チュートリアルの5章で作成したヘッドラインの特徴量をpkl化したファイルkeywords_features.pkl | 本チュートリアルの5章で作成したキーワードの特徴量をpkl化したファイル
headline_features.zip | 本チュートリアルの6章で作成したヘッドラインの特徴量及びsentiment scoreをpkl化したファイル
keywords_features.zip | 本チュートリアルの6章で作成したキーワードの特徴量及びsentiment scoreをpkl化したファイル


> boundry_weekは26とし、trainとtestを52週の半分、つまり、2020年前半のニュースを訓練用データ、2020年後半のニュースをテストデータとしています。

> 学習を行ってみましょう。n_epochは全てのデータを一度用いた学習回数を表し、ここでは、テストであるため1と設定しています。

との記載があるので現状使用している結果はまるで収束していない学習結果となっている可能性がある。

**Comment by dondakeshimo** [comment]
BERTの部分も十分に学習されていない可能性があるのでチュートリアルを真面目に呼んで再学習の必要性を調べる。

**Comment by dondakeshimo** [comment]
雰囲気BERTは大丈夫そう。
LSTMの部分だけ再度学習する必要があるとして今回はすすめる。

**Comment by dondakeshimo** [comment]
### チュートリアル6章のLSTMにおける課題点

- trainデータが26週分しかない
  - ~全データはもうちょいあるはずだが、実行速度を考慮しているっぽい~
  - 2020年分のデータしかなかった
- ~epockが1しかない~
  - ~実行速度の観点からと思われる~
  - めっちゃ20回くらい回していた
- headline, keywordsの両特徴量に対して何故かバラバラのモデルを作成しているっぽい
  - 混ぜれば良くない？そうでもない？

**Comment by dondakeshimo** [comment]
もしかしてBERTで抽出できている特徴量は事前に用意されている分だけで、新しいニュースのBERT特徴量抽出はコードに組まれていないかもしれない。

**Comment by dondakeshimo** [comment]
### 現状のメモリ使用量
32GiBのメモリを搭載したPCでプログラムを回して実行中topを監視するという至極原始的な手法でメモリ使用量を計測したところ最大で17.2%となった。よって空間計算量は現状5.5GiB程度ということになる。
メモリに倍くらいの余裕はあるが、33セクター分のニューラルネットワークを載せる余裕があるとは思えない。

**Comment by dondakeshimo** [comment]
TODO 

- [x] 2021年分のBERT特徴量を都度計算するようになっているか確認する
- [x] ~epock数を増やして回すために~ trainが回ることを確認する
- [x] ニューラルネットワークの再構築の方法を考える

**Comment by dondakeshimo** [comment]
![Image from iOS](https://user-images.githubusercontent.com/23194960/117138087-870fae80-ade5-11eb-9b83-1d5b01c9adfe.jpg)

**Comment by dondakeshimo** [comment]
おそらくデータが少ないため、train自体は一瞬で終わるので再度やり直すのは特に問題ない。
問題としては特に触ったことのないPyTorchでニューラルネットワークを組み直す必要がありそうな部分だが、1日くらい使えばなんとかなると思われる。
